name: "Formatting check"
on:
  pull_request:
  push:
jobs:
  nixfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: jitterbit/get-changed-files@v1
      id: files
    - name: global changed files nixfmt
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          nixfmt --check "${changed_file}";
        done
