name: "Formatting check"
on:
  pull_request:
  push:
jobs:
  nixfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
    - name: global nixfmt
      run: nix-shell -p nixfmt findutils --run "nixfmt --check $(find . -name '*.nix' -print)"
